const firebaseConfig={apiKey:'AIzaSyDJja4KxdCJ-GZ7lE_krRMoX7dF5RGtSKw',authDomain:'hearthstone-real-estate-crm.firebaseapp.com',projectId:'hearthstone-real-estate-crm',storageBucket:'hearthstone-real-estate-crm.firebasestorage.app',messagingSenderId:'694415647324',appId:'1:694415647324:web:f8bf3a1e9b529b0f1c3c99'};
const CRM_OWNER_EMAIL='e.hepp19@gmail.com';
let cloudUser=null,cloudDocument=null,cloudUnsubscribe=null,cloudWriteTimer=null,applyingCloud=false;

function cloudSafe(source){const value=copy(source);value.tables??={};value.tables.contact_documents=[];value.tables.transaction_documents=[];return value}
function syncButton(){let button=document.querySelector('#cloudSyncBtn');if(!button){button=document.createElement('button');button.id='cloudSyncBtn';button.className='btn sync-button';document.querySelector('.avatar')?.before(button)}return button}
function showSyncState(label,kind=''){const button=syncButton();if(!button)return;button.textContent=label;button.dataset.state=kind;button.disabled=kind==='busy'}
async function signInForSync(){showSyncState('Signing in…','busy');const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({login_hint:CRM_OWNER_EMAIL});try{if(/iPhone|iPad|iPod/i.test(navigator.userAgent))await firebase.auth().signInWithRedirect(provider);else await firebase.auth().signInWithPopup(provider)}catch(error){showSyncState('Sign in to sync','error');alert(`Google sign-in could not start: ${error.message}`)}}
function installSignInButton(){const button=syncButton();if(!button)return;button.disabled=false;button.textContent='Sign in to sync';button.dataset.state='signed-out';button.onclick=signInForSync}
async function refreshVisibleView(){if(document.querySelector('#modal:not(.hidden)'))return;if(typeof go==='function'&&state?.view)await go(state.view)}
async function receiveCloud(snapshot){if(!cloudDocument)return;const current=await read();if(!snapshot.exists){showSyncState('Uploading CRM…','busy');await cloudDocument.set(cloudSafe(current));showSyncState('✓ Synced','synced');return}const incoming=snapshot.data(),merged=merge(current,incoming),safeMerged=cloudSafe(merged);applyingCloud=true;try{await write(merged)}finally{applyingCloud=false}if(JSON.stringify(safeMerged)!==JSON.stringify(incoming))await cloudDocument.set(safeMerged);showSyncState(navigator.onLine?'✓ Synced':'Offline — saved','synced');await refreshVisibleView()}
async function connectCloud(user){if(user.email?.toLowerCase()!==CRM_OWNER_EMAIL){await firebase.auth().signOut();alert('This CRM is restricted to the owner’s Google account.');return}cloudUser=user;cloudDocument=firebase.firestore().doc(`users/${user.uid}/crm/main`);showSyncState('Connecting…','busy');cloudUnsubscribe?.();cloudUnsubscribe=cloudDocument.onSnapshot(receiveCloud,error=>{console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')});const button=syncButton();if(button)button.onclick=null}
async function initializeCloudSync(){if(!window.firebase){installSignInButton();showSyncState('Sync unavailable','error');return}firebase.initializeApp(firebaseConfig);try{await firebase.firestore().enablePersistence({synchronizeTabs:true})}catch(error){if(!['failed-precondition','unimplemented'].includes(error.code))console.warn(error)}await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);firebase.auth().onAuthStateChanged(user=>user?connectCloud(user):installSignInButton());window.addEventListener('online',()=>cloudUser&&showSyncState('Reconnecting…','busy'));window.addEventListener('offline',()=>cloudUser&&showSyncState('Offline — saved','synced'))}
document.addEventListener('crm:local-write',event=>{if(applyingCloud||!cloudDocument)return;clearTimeout(cloudWriteTimer);showSyncState(navigator.onLine?'Syncing…':'Offline — saved',navigator.onLine?'busy':'synced');cloudWriteTimer=setTimeout(async()=>{try{await cloudDocument.set(cloudSafe(event.detail.state));showSyncState('✓ Synced','synced')}catch(error){console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')}},500)});
window.addEventListener('DOMContentLoaded',initializeCloudSync);
