const firebaseConfig={apiKey:'AIzaSyDJja4KxdCJ-GZ7lE_krRMoX7dF5RGtSKw',authDomain:'hearthstone-real-estate-crm.firebaseapp.com',projectId:'hearthstone-real-estate-crm',storageBucket:'hearthstone-real-estate-crm.firebasestorage.app',messagingSenderId:'694415647324',appId:'1:694415647324:web:f8bf3a1e9b529b0f1c3c99'};
const CRM_LEGACY_EMAIL='e.hepp19@gmail.com',CRM_OWNER_EMAIL='erichepple7@gmail.com',CRM_ALLOWED_EMAILS=[CRM_LEGACY_EMAIL,CRM_OWNER_EMAIL];
let cloudUser=null,cloudDocument=null,legacyDocument=null,cloudUnsubscribe=null,cloudWriteTimer=null,applyingCloud=false,cloudFileUploadRunning=false;

function cloudSafe(source){const value=copy(source);value.tables??={};for(const table of ['contact_documents','transaction_documents'])value.tables[table]=(value.tables[table]||[]).filter(x=>x.cloud_file_id&&(!cloudUser||!x.cloud_owner_uid||x.cloud_owner_uid===cloudUser.uid)).map(({data,...document})=>document);delete value.device_id;delete value.modified_at;return value}
const cloudFileRef=(fileId,chunk)=>firebase.firestore().doc(`users/${cloudUser.uid}/crm/file-${fileId}-${chunk}`);
async function uploadCloudFile(document,data){if(!cloudUser||!data)throw Error('Sign in and connect to the internet before uploading this document.');const base64=String(data).split(',')[1]||'',chunkSize=600000,chunks=Math.ceil(base64.length/chunkSize),fileId=String(document.id);for(let index=0;index<chunks;index++)await cloudFileRef(fileId,index).set({data:base64.slice(index*chunkSize,(index+1)*chunkSize),index,updated_at:new Date().toISOString()});return {cloud_file_id:fileId,cloud_chunks:chunks,cloud_owner_uid:cloudUser.uid,cloud_synced_at:new Date().toISOString()}}
async function fetchCloudFile(document){if(document.data)return document.data;if(!cloudUser||!document.cloud_file_id)throw Error('This document is not available on this device yet. Connect to the internet and tap Sync.');const snapshots=await Promise.all(Array.from({length:Number(document.cloud_chunks||0)},(_,index)=>cloudFileRef(document.cloud_file_id,index).get())),base64=snapshots.map(x=>x.data()?.data||'').join('');if(!base64)throw Error('The cloud document could not be downloaded.');return `data:${document.mime_type||'application/octet-stream'};base64,${base64}`}
async function deleteCloudFile(document){if(!cloudUser||!document?.cloud_file_id)return;await Promise.all(Array.from({length:Number(document.cloud_chunks||0)},(_,index)=>cloudFileRef(document.cloud_file_id,index).delete()))}
async function syncPendingDocumentFiles(){if(cloudFileUploadRunning||!cloudUser||!navigator.onLine)return;cloudFileUploadRunning=true;try{const current=await read();let changed=false;for(const table of ['contact_documents','transaction_documents'])for(const document of current.tables[table]||[]){if(!document.data&&document.cloud_file_id&&(!document.cloud_owner_uid||document.cloud_owner_uid===cloudUser.uid)){document.data=await fetchCloudFile(document);changed=true}if(document.data&&(!document.cloud_file_id||document.cloud_owner_uid!==cloudUser.uid)){const uploaded=await uploadCloudFile(document,document.data);Object.assign(document,uploaded,{_modified_at:new Date().toISOString()});changed=true}}if(changed){applyingCloud=true;try{await write(current)}finally{applyingCloud=false}await cloudDocument.set(cloudSafe(current));showSyncState('✓ Documents synced','synced')}}catch(error){console.error(error);showSyncState('Document sync error','error');throw error}finally{cloudFileUploadRunning=false}}
async function createDailyBackup(source){if(!cloudUser||!navigator.onLine)return;const day=new Date().toISOString().slice(0,10),key=`crm-backup-${day}`,last=localStorage.getItem('crm_last_cloud_backup');if(last===day)return;await firebase.firestore().doc(`users/${cloudUser.uid}/crm/${key}`).set({created_at:new Date().toISOString(),state:cloudSafe(source)});localStorage.setItem('crm_last_cloud_backup',day)}
window.crmCloudFiles={uploadDocument:uploadCloudFile,fetchDocument:fetchCloudFile,deleteDocument:deleteCloudFile};
function syncButton(){let button=document.querySelector('#cloudSyncBtn');if(!button){button=document.createElement('button');button.id='cloudSyncBtn';button.className='btn sync-button';document.querySelector('.avatar')?.before(button)}return button}
function migrationButton(){let button=document.querySelector('#accountMigrationBtn');if(!button){button=document.createElement('button');button.id='accountMigrationBtn';button.className='btn migration-button';syncButton().before(button)}return button}
function updateMigrationButton(){const existing=document.querySelector('#accountMigrationBtn');if(cloudUser?.email?.toLowerCase()===CRM_LEGACY_EMAIL&&!localStorage.getItem('crm_account_migration_complete')){const button=migrationButton();button.textContent='Move Google account';button.disabled=false;button.onclick=prepareAccountTransfer}else existing?.remove()}
async function prepareAccountTransfer(){const button=migrationButton();button.disabled=true;button.textContent='Preparing safe transfer…';showSyncState('Protecting documents…','busy');try{await syncPendingDocumentFiles();const current=await read(),documents=[...(current.tables.contact_documents||[]),...(current.tables.transaction_documents||[])],missing=documents.filter(x=>!x.data);if(missing.length)throw Error(`${missing.length} document${missing.length===1?' is':'s are'} not available for transfer.`);await cloudDocument.set(cloudSafe(current));localStorage.removeItem('crm_last_cloud_backup');await createDailyBackup(current);localStorage.setItem('crm_account_migration_ready','1');alert('Safe transfer copy prepared. Next, sign in with erichepple7@gmail.com. The old Google-account copy will remain untouched.');cloudUnsubscribe?.();cloudUnsubscribe=null;cloudUser=null;cloudDocument=null;legacyDocument=null;await firebase.auth().signOut()}catch(error){console.error(error);button.disabled=false;button.textContent='Try account transfer again';showSyncState('Transfer preparation stopped','error');alert(`The account was not changed. ${error.message}`)}}
function showSyncState(label,kind=''){const button=syncButton();if(!button)return;button.textContent=label;button.dataset.state=kind;button.disabled=kind==='busy'}
async function signInForSync(){showSyncState('Signing in…','busy');const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({login_hint:CRM_OWNER_EMAIL,prompt:'select_account'});try{await firebase.auth().signInWithPopup(provider)}catch(error){console.error(error);showSyncState('Try sign in again','error');alert('Google sign-in did not finish. Close any open Google sign-in window, then tap “Try sign in again.”')}}
function installSignInButton(){document.querySelector('#accountMigrationBtn')?.remove();const button=syncButton();if(!button)return;button.disabled=false;button.textContent=localStorage.getItem('crm_account_migration_ready')?'Sign in with new Google account':'Sign in to sync';button.dataset.state='signed-out';button.onclick=signInForSync}
async function refreshVisibleView(){if(document.querySelector('#modal:not(.hidden)'))return;if(typeof go==='function'&&state?.view)await go(state.view)}
async function receiveCloud(snapshot){if(!cloudDocument)return;const current=await read();if(!snapshot.exists){showSyncState('Uploading CRM…','busy');await cloudDocument.set(cloudSafe(current));showSyncState('✓ Synced','synced');return}const incoming=snapshot.data(),merged=merge(current,incoming),safeMerged=cloudSafe(merged);applyingCloud=true;try{await write(merged)}finally{applyingCloud=false}if(JSON.stringify(safeMerged)!==JSON.stringify(incoming))await cloudDocument.set(safeMerged);showSyncState(navigator.onLine?'✓ Synced':'Offline — saved','synced');await refreshVisibleView()}
async function syncFromServer(){if(!cloudDocument)return;showSyncState('Checking cloud…','busy');try{const [current,legacy]=await Promise.all([cloudDocument.get({source:'server'}),legacyDocument.get({source:'server'})]);if(legacy.exists)await receiveCloud(legacy);await receiveCloud(current);showSyncState('✓ Synced','synced')}catch(error){console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')}}
async function connectCloud(user){const email=user.email?.toLowerCase();if(!CRM_ALLOWED_EMAILS.includes(email)){await firebase.auth().signOut();alert('This CRM is restricted to the owner’s Google accounts.');return}if(email===CRM_LEGACY_EMAIL&&localStorage.getItem('crm_account_migration_ready')){await firebase.auth().signOut();alert('Choose erichepple7@gmail.com to finish the CRM transfer.');return}cloudUser=user;cloudDocument=firebase.firestore().doc(`users/${user.uid}/crm/main-v2`);legacyDocument=firebase.firestore().doc(`users/${user.uid}/crm/main`);showSyncState('Connecting…','busy');cloudUnsubscribe?.();cloudUnsubscribe=cloudDocument.onSnapshot(receiveCloud,error=>{console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')});const button=syncButton();if(button){button.disabled=false;button.onclick=syncFromServer;button.title='Check for updates from your other devices'}updateMigrationButton();legacyDocument.get({source:'server'}).then(snapshot=>snapshot.exists&&receiveCloud(snapshot)).catch(console.warn);const current=await read();await syncPendingDocumentFiles();const latest=await read();await cloudDocument.set(cloudSafe(latest));await createDailyBackup(latest).catch(console.error);if(email===CRM_OWNER_EMAIL&&localStorage.getItem('crm_account_migration_ready')){localStorage.setItem('crm_account_migration_complete','1');localStorage.removeItem('crm_account_migration_ready');updateMigrationButton();showSyncState('✓ Account moved','synced');alert('CRM transfer complete. Your records and documents are now connected to erichepple7@gmail.com.')}}
async function initializeCloudSync(){if(!window.firebase){installSignInButton();showSyncState('Sync unavailable','error');return}try{firebase.initializeApp(firebaseConfig);try{await firebase.firestore().enablePersistence({synchronizeTabs:true})}catch(error){if(!['failed-precondition','unimplemented'].includes(error.code))console.warn(error)}await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);firebase.auth().onAuthStateChanged(user=>user?connectCloud(user):installSignInButton());window.addEventListener('online',()=>cloudUser&&showSyncState('Reconnecting…','busy'));window.addEventListener('offline',()=>cloudUser&&showSyncState('Offline — saved','synced'))}catch(error){console.error(error);installSignInButton();showSyncState('Try sign in again','error')}}
document.addEventListener('crm:local-write',event=>{if(applyingCloud||!cloudDocument)return;clearTimeout(cloudWriteTimer);showSyncState(navigator.onLine?'Syncing…':'Offline — saved',navigator.onLine?'busy':'synced');cloudWriteTimer=setTimeout(async()=>{try{await syncPendingDocumentFiles();const latest=await read();await cloudDocument.set(cloudSafe(latest));await createDailyBackup(latest);showSyncState('✓ Synced','synced')}catch(error){console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')}},500)});
document.addEventListener('crm:document-delete',event=>deleteCloudFile(event.detail).catch(console.error));
window.addEventListener('DOMContentLoaded',initializeCloudSync);
