const firebaseConfig={apiKey:'AIzaSyDJja4KxdCJ-GZ7lE_krRMoX7dF5RGtSKw',authDomain:'hearthstone-real-estate-crm.firebaseapp.com',projectId:'hearthstone-real-estate-crm',storageBucket:'hearthstone-real-estate-crm.firebasestorage.app',messagingSenderId:'694415647324',appId:'1:694415647324:web:f8bf3a1e9b529b0f1c3c99'};
const CRM_OWNER_EMAIL='e.hepp19@gmail.com';
const CLOUD_DIRTY_KEY='crm_cloud_pending_changes';
let cloudUser=null,cloudDocument=null,legacyDocument=null,cloudUnsubscribe=null,openHouseUnsubscribe=null,cloudWriteTimer=null,cloudRefreshTimer=null,applyingCloud=false,cloudFileUploadRunning=false,cloudSyncRunning=false,openHouseImportRunning=false,publicListingPublishRunning=false;

function cloudSafe(source){const value=copy(source);value.tables??={};for(const table of ['contact_documents','transaction_documents'])value.tables[table]=(value.tables[table]||[]).filter(x=>x.cloud_file_id).map(({data,...document})=>document);delete value.device_id;delete value.modified_at;return value}
function publicListingSafe(listing){const allowed=['id','address','mls','current_price','bedrooms','bathrooms','square_feet','pool','area','important_features','public_description','feature_highlights','hero_image_url','gallery_urls','virtual_tour_url','public_listing_url','flyer_url','public_documents','status'];return Object.fromEntries(allowed.map(key=>[key,listing[key]??(key.endsWith('_urls')||['feature_highlights','public_documents'].includes(key)?[]:'')]))}
async function publishPublicListings(source){if(publicListingPublishRunning||!cloudUser||!navigator.onLine)return;publicListingPublishRunning=true;try{for(const listing of source.tables.listings||[]){const ref=firebase.firestore().collection('public_listings').doc(String(listing.id)),value=publicListingSafe(listing),snapshot=await ref.get({source:'server'});if(!snapshot.exists||JSON.stringify(snapshot.data())!==JSON.stringify(value))await ref.set(value)}}catch(error){console.error('Public listing publish:',error)}finally{publicListingPublishRunning=false}}
const cloudFileRef=(fileId,chunk)=>firebase.firestore().doc(`users/${cloudUser.uid}/crm/file-${fileId}-${chunk}`);
async function uploadCloudFile(document,data){if(!cloudUser||!data)throw Error('Sign in and connect to the internet before uploading this document.');const base64=String(data).split(',')[1]||'',chunkSize=600000,chunks=Math.ceil(base64.length/chunkSize),fileId=String(document.id);for(let index=0;index<chunks;index++)await cloudFileRef(fileId,index).set({data:base64.slice(index*chunkSize,(index+1)*chunkSize),index,updated_at:new Date().toISOString()});return {cloud_file_id:fileId,cloud_chunks:chunks,cloud_synced_at:new Date().toISOString()}}
async function fetchCloudFile(document){if(document.data)return document.data;if(!cloudUser||!document.cloud_file_id)throw Error('This document is not available on this device yet. Connect to the internet and tap Sync.');const snapshots=await Promise.all(Array.from({length:Number(document.cloud_chunks||0)},(_,index)=>cloudFileRef(document.cloud_file_id,index).get())),base64=snapshots.map(x=>x.data()?.data||'').join('');if(!base64)throw Error('The cloud document could not be downloaded.');return `data:${document.mime_type||'application/octet-stream'};base64,${base64}`}
async function deleteCloudFile(document){if(!cloudUser||!document?.cloud_file_id)return;await Promise.all(Array.from({length:Number(document.cloud_chunks||0)},(_,index)=>cloudFileRef(document.cloud_file_id,index).delete()))}
async function syncPendingDocumentFiles(){if(cloudFileUploadRunning||!cloudUser||!navigator.onLine)return;cloudFileUploadRunning=true;try{const current=await read();let changed=false;for(const table of ['contact_documents','transaction_documents'])for(const document of current.tables[table]||[])if(document.data&&!document.cloud_file_id){const uploaded=await uploadCloudFile(document,document.data);Object.assign(document,uploaded,{_modified_at:new Date().toISOString()});changed=true}if(changed){applyingCloud=true;try{await write(current)}finally{applyingCloud=false}showSyncState('✓ Documents ready','synced');setTimeout(syncFromServer,0)}}catch(error){console.error(error);showSyncState('Document sync error','error')}finally{cloudFileUploadRunning=false}}
async function createDailyBackup(source){if(!cloudUser||!navigator.onLine)return;const day=new Date().toISOString().slice(0,10),key=`crm-backup-${day}`,last=localStorage.getItem('crm_last_cloud_backup');if(last===day)return;await firebase.firestore().doc(`users/${cloudUser.uid}/crm/${key}`).set({created_at:new Date().toISOString(),state:cloudSafe(source)});localStorage.setItem('crm_last_cloud_backup',day)}
window.crmCloudFiles={uploadDocument:uploadCloudFile,fetchDocument:fetchCloudFile,deleteDocument:deleteCloudFile};
function syncButton(){let button=document.querySelector('#cloudSyncBtn');if(!button){button=document.createElement('button');button.id='cloudSyncBtn';button.className='btn sync-button';document.querySelector('.avatar')?.before(button)}return button}
function showSyncState(label,kind=''){const button=syncButton();if(!button)return;button.textContent=label;button.dataset.state=kind;button.disabled=kind==='busy'}
async function signInForSync(){showSyncState('Signing in…','busy');const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({login_hint:CRM_OWNER_EMAIL,prompt:'select_account'});try{await firebase.auth().signInWithPopup(provider)}catch(error){console.error(error);showSyncState('Try sign in again','error');alert('Google sign-in did not finish. Close any open Google sign-in window, then tap “Try sign in again.”')}}
function installSignInButton(){const button=syncButton();if(!button)return;button.disabled=false;button.textContent='Sign in to sync';button.dataset.state='signed-out';button.onclick=signInForSync}
async function refreshVisibleView(){if(document.querySelector('#modal:not(.hidden)'))return;const contactId=state?.contact?.id;if(contactId&&typeof showContact==='function')return showContact(contactId);if(typeof go==='function'&&state?.view)await go(state.view)}
async function receiveCloud(snapshot){if(!cloudDocument)return;const current=await read();if(!snapshot.exists){showSyncState('Uploading CRM…','busy');setTimeout(syncFromServer,0);return}const incoming=snapshot.data(),merged=merge(current,incoming),safeMerged=cloudSafe(merged);applyingCloud=true;try{await write(merged)}finally{applyingCloud=false}if(JSON.stringify(safeMerged)!==JSON.stringify(incoming))setTimeout(syncFromServer,0);showSyncState(navigator.onLine?'✓ Synced':'Offline — saved','synced');await refreshVisibleView()}
async function syncFromServer(){
 if(!cloudDocument||!navigator.onLine||cloudSyncRunning)return;
 cloudSyncRunning=true;showSyncState('Checking cloud…','busy');
 try{
  const legacySnapshot=await legacyDocument.get({source:'server'});
  let localState=await read();
  if(legacySnapshot.exists)localState=merge(localState,legacySnapshot.data());
  const merged=await firebase.firestore().runTransaction(async transaction=>{
   const latestSnapshot=await transaction.get(cloudDocument);
   const latest=latestSnapshot.exists?latestSnapshot.data():{tables:{},deleted:{}};
   const reconciled=merge(copy(localState),latest);
   transaction.set(cloudDocument,cloudSafe(reconciled));
   return reconciled;
  });
  applyingCloud=true;try{await write(merged)}finally{applyingCloud=false}
  localStorage.removeItem(CLOUD_DIRTY_KEY);
  showSyncState('✓ Synced','synced');
  await publishPublicListings(merged);
  await refreshVisibleView();
 }catch(error){console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')}
 finally{cloudSyncRunning=false}
}
async function importOpenHouseSubmissions(snapshot){if(openHouseImportRunning||snapshot.empty)return;openHouseImportRunning=true;try{for(const document of snapshot.docs){const lead=document.data(),current=await read(),email=String(lead.email||'').trim().toLowerCase(),phone=String(lead.phone||'').replace(/\D/g,''),existing=(current.tables.contacts||[]).find(c=>(email&&String(c.email||'').trim().toLowerCase()===email)||(phone&&String(c.phone||'').replace(/\D/g,'')===phone));const roles=String(lead.role||'Buyer').split(',').filter(x=>['Buyer','Seller'].includes(x));let contact;if(existing){contact=await localApi(`/contacts/${existing.id}`,{method:'PUT',body:JSON.stringify({...existing,roles:[...new Set([...(existing.roles||[]),...roles])],budget_min:Number(lead.budget_min||existing.budget_min||0),budget_max:Number(lead.budget_max||existing.budget_max||0),bedrooms:Number(lead.bedrooms||existing.bedrooms||0),pool:lead.pool||existing.pool||'',area:lead.area||existing.area||'',important_feature:lead.important_feature||existing.important_feature||''})});const after=await read();for(const role of roles){const type=role.toLowerCase();if(!(after.tables.opportunities||[]).some(x=>x.contact_id===contact.id&&x.type===type&&x.status!=='closed'))await localApi('/opportunities',{method:'POST',body:JSON.stringify({contact_id:contact.id,type,stage:'New Lead',title:`${role} opportunity`,value:0,details:{},status:'active'})})}}else{contact=await localApi('/contacts',{method:'POST',body:JSON.stringify({first_name:lead.first_name,last_name:lead.last_name,phone:lead.phone,email:lead.email,preferred_contact:'Text',source:'Open House',roles,budget_min:Number(lead.budget_min||0),budget_max:Number(lead.budget_max||0),bedrooms:Number(lead.bedrooms||0),pool:lead.pool||'',area:lead.area||'',important_feature:lead.important_feature||'',tags:['Open House Sign-in'],notes:[lead.timeframe&&`Timeframe: ${lead.timeframe}`,lead.agent_status&&`Working with agent: ${lead.agent_status}`,lead.preapproved&&`Financing: ${lead.preapproved}`,lead.listing_address&&`Visited: ${lead.listing_address}`].filter(Boolean).join('\n'),apply_plan:true})})}
await localApi('/activities',{method:'POST',body:JSON.stringify({contact_id:contact.id,type:'Note',direction:'Incoming',subject:`Open-house sign-in — ${lead.listing_address||'Property'}`,body:`Submitted from QR sign-in. Timeframe: ${lead.timeframe||'Not provided'}.`,occurred_at:new Date().toISOString().slice(0,10),listing_id:Number(lead.listing_id)||null,open_house_submission_id:document.id})});
const latest=await read();
const thankYouText=`Hi, this is Eric Hepple with Paradise Property Brokers Inc, thank you for stopping by my open house at ${lead.listing_address||'the property'}! What did you think of the property?`;
if(!(latest.tables.communication_drafts||[]).some(x=>x.source_id===document.id))await localApi('/communication_drafts',{method:'POST',body:JSON.stringify({contact_id:contact.id,channel:'Text',subject:'Open house thank you',body:thankYouText,status:'draft',source:'Open house sign-in',source_id:document.id})});
if(!(latest.tables.notifications||[]).some(x=>x.source_id===document.id))await localApi('/notifications',{method:'POST',body:JSON.stringify({type:'open_house_sign_in',source_id:document.id,contact_id:contact.id,title:`${lead.first_name} ${lead.last_name} signed in`,message:lead.listing_address||'Open house',action_label:'Text Thank You',action_phone:lead.phone||contact.phone||'',action_body:thankYouText,read:false})});
await document.ref.update({imported:true,imported_at:firebase.firestore.FieldValue.serverTimestamp(),imported_by:cloudUser.uid});if(typeof refreshNotifications==='function')refreshNotifications();if(typeof toast==='function')toast(`New open-house lead: ${lead.first_name} ${lead.last_name}`)}}catch(error){console.error(error);showSyncState('Lead import error','error')}finally{openHouseImportRunning=false}}
function watchOpenHouseSubmissions(){openHouseUnsubscribe?.();openHouseUnsubscribe=firebase.firestore().collection('open_house_submissions').where('imported','==',false).onSnapshot(importOpenHouseSubmissions,error=>console.error('Open-house intake:',error))}
async function connectCloud(user){if(user.email?.toLowerCase()!==CRM_OWNER_EMAIL){await firebase.auth().signOut();alert('This CRM is restricted to the owner’s Google account.');return}cloudUser=user;cloudDocument=firebase.firestore().doc(`users/${user.uid}/crm/main-v2`);legacyDocument=firebase.firestore().doc(`users/${user.uid}/crm/main`);showSyncState('Connecting…','busy');cloudUnsubscribe?.();cloudUnsubscribe=cloudDocument.onSnapshot(receiveCloud,error=>{console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')});watchOpenHouseSubmissions();const button=syncButton();if(button){button.disabled=false;button.onclick=syncFromServer;button.title='Check for updates from your other devices'}legacyDocument.get({source:'server'}).then(snapshot=>snapshot.exists&&receiveCloud(snapshot)).catch(console.warn);const current=await read();createDailyBackup(current).catch(console.error);syncPendingDocumentFiles()}
async function initializeCloudSync(){if(!window.firebase){installSignInButton();showSyncState('Sync unavailable','error');return}try{firebase.initializeApp(firebaseConfig);try{await firebase.firestore().enablePersistence({synchronizeTabs:true})}catch(error){if(!['failed-precondition','unimplemented'].includes(error.code))console.warn(error)}await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL);firebase.auth().onAuthStateChanged(user=>user?connectCloud(user):installSignInButton());window.addEventListener('online',()=>cloudUser&&showSyncState('Reconnecting…','busy'));window.addEventListener('offline',()=>cloudUser&&showSyncState('Offline — saved','synced'))}catch(error){console.error(error);installSignInButton();showSyncState('Try sign in again','error')}}
document.addEventListener('crm:local-write',event=>{if(applyingCloud)return;localStorage.setItem(CLOUD_DIRTY_KEY,new Date().toISOString());if(!cloudDocument)return;clearTimeout(cloudWriteTimer);showSyncState(navigator.onLine?'Syncing…':'Offline — saved',navigator.onLine?'busy':'synced');cloudWriteTimer=setTimeout(async()=>{try{if(!navigator.onLine)return;await syncPendingDocumentFiles();await syncFromServer();await createDailyBackup(await read())}catch(error){console.error(error);showSyncState(navigator.onLine?'Sync error':'Offline — saved','error')}},500)});
document.addEventListener('crm:document-delete',event=>deleteCloudFile(event.detail).catch(console.error));
window.addEventListener('online',()=>{if(cloudUser){showSyncState('Reconnecting…','busy');syncFromServer()}});
window.addEventListener('pageshow',()=>cloudUser&&navigator.onLine&&syncFromServer());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&cloudUser&&navigator.onLine)syncFromServer()});
cloudRefreshTimer=setInterval(()=>cloudUser&&navigator.onLine&&syncFromServer(),60000);
window.addEventListener('DOMContentLoaded',initializeCloudSync);
