const DB_NAME='hearthstone-offline-crm',STORE='state',KEY='main';
const tableNames=['contacts','opportunities','listings','transactions','tasks','activities','action_plans','communication_drafts','transaction_checklist','transaction_documents','contact_documents','milestone_reminders','notifications'];
const params=new URLSearchParams(location.search);
if(params.get('offline')==='1')localStorage.setItem('hearthstone_offline','1');
const offlineMode=localStorage.getItem('hearthstone_offline')==='1'||location.protocol==='file:';

const plans=[
 ['Open House Follow-up','Open House',[[0,'Call and thank for visiting'],[1,'Send matching listings'],[3,'Check property feedback'],[7,'Schedule buyer consultation']]],
 ['Website Lead Sprint','Website',[[0,'Call new inquiry'],[1,'Send tailored search'],[3,'Follow up'],[7,'Confirm search criteria'],[14,'Nurture check-in']]],
 ['Social Lead Welcome','Social Media',[[0,'Send welcome message'],[2,'Call to learn goals'],[7,'Share market update']]],
 ['Referral VIP','Referral',[[0,'Call and mention referral source'],[1,'Send introduction'],[5,'Schedule consultation']]]
];
const fresh=()=>({version:1,device_id:crypto.randomUUID(),tables:Object.fromEntries(tableNames.map(x=>[x,[]])),deleted:{},modified_at:new Date().toISOString()});
function seed(state){
 state.tables??={};for(const table of tableNames)state.tables[table]??=[];state.deleted??={};
 state.tables.tasks=(state.tables.tasks||[]).map(task=>{const normalized={priority:'Medium',reminder_minutes:0,completed_at:null,reminder_sent_at:null,...task};if(!String(normalized.status||'').trim())normalized.status=normalized.completed_at?'completed':'open';return normalized});
 if(!state.tables.action_plans.length)state.tables.action_plans=plans.map((p,i)=>({id:i+1,name:p[0],source:p[1],active:1,steps:p[2].map(([day,title])=>({day,title})),created_at:new Date().toISOString(),_modified_at:new Date().toISOString()}));return state
}
const openDb=()=>new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
async function read(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE),request=tx.objectStore(STORE).get(KEY);request.onsuccess=()=>resolve(seed(request.result||fresh()));request.onerror=()=>reject(request.error);tx.oncomplete=()=>db.close()})}
async function write(state){state.modified_at=new Date().toISOString();const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state,KEY);tx.oncomplete=()=>{db.close();document.dispatchEvent(new CustomEvent('crm:local-write',{detail:{state:copy(state)}}));resolve(state)};tx.onerror=()=>reject(tx.error)})}
const copy=x=>structuredClone(x), now=()=>new Date().toISOString(), newId=()=>Date.now()*1000+crypto.getRandomValues(new Uint32Array(1))[0]%1000;
const body=opts=>opts?.body?JSON.parse(opts.body):{};
const touch=row=>({...row,_modified_at:now()});
const contactName=(state,id)=>{const c=state.tables.contacts.find(x=>x.id===Number(id));return c?`${c.first_name} ${c.last_name}`:''};
function list(state,table){let rows=copy(state.tables[table]||[]);if(table==='opportunities')rows=rows.map(x=>({...x,contact_name:contactName(state,x.contact_id)}));if(table==='listings')rows=rows.map(x=>({...x,seller_name:contactName(state,x.seller_id),dom:x.listing_date?Math.max(0,Math.floor((Date.now()-new Date(x.listing_date).getTime())/864e5)):null}));if(table==='transactions')rows=rows.map(x=>({...x,buyer_name:contactName(state,x.buyer_id),seller_name:contactName(state,x.seller_id)}));if(['tasks','activities','communication_drafts'].includes(table))rows=rows.map(x=>({...x,contact_name:contactName(state,x.contact_id)}));return rows}
function dashboard(state){const day=new Date().toISOString().slice(0,10),in30=new Date(Date.now()+30*864e5).toISOString().slice(0,10),open=state.tables.tasks.filter(x=>x.status==='open');return {newLeads:state.tables.contacts.filter(x=>(x.created_at||'').slice(0,10)>=new Date(Date.now()-7*864e5).toISOString().slice(0,10)).length,needsAttention:new Set(open.filter(x=>(x.due_at||'').slice(0,10)<=day).map(x=>x.contact_id).filter(Boolean)).size,activeBuyers:state.tables.opportunities.filter(x=>x.type==='buyer'&&x.status!=='closed'&&!['Closed','Nurture/Lost'].includes(x.stage)).length,activeSellers:state.tables.opportunities.filter(x=>x.type==='seller'&&x.status!=='closed'&&!['Closed','Nurture/Lost'].includes(x.stage)).length,activeListings:state.tables.listings.filter(x=>x.status==='Active').length,underContract:state.tables.transactions.filter(x=>x.status==='Under Contract').length,upcomingClosings:state.tables.transactions.filter(x=>(x.closing_date||'').slice(0,10)>=day&&(x.closing_date||'').slice(0,10)<=in30).length,dueToday:open.filter(x=>(x.due_at||'').slice(0,10)===day).length,overdue:open.filter(x=>(x.due_at||'').slice(0,10)<day).length}}
function suggestedMessage(contact,title){const first=contact.first_name||'there',lower=String(title).toLowerCase(),channel=lower.includes('text')||lower.includes('message')?'Text':'Email',subject=lower.includes('listing')?'Listings selected for you':lower.includes('introduction')?'Nice to meet you':'Checking in',body=lower.includes('listing')?`Hi ${first},\n\nI found a few properties that may fit what you are looking for. I would be happy to review them with you and adjust the search based on your feedback.\n\nEric Hepple\nParadise Property Brokers Inc`:`Hi ${first},\n\nI wanted to check in and see how I can help with your real-estate plans. When you have a moment, let me know what questions you have or what your next step looks like.\n\nEric Hepple\nParadise Property Brokers Inc`;return {channel,subject,body}}
function applyPlan(state,contact){const plan=state.tables.action_plans.find(x=>x.active&&x.source?.toLowerCase()===contact.source?.toLowerCase());if(!plan)return 0;for(const step of plan.steps){const due=new Date(Date.now()+Number(step.day)*864e5);due.setHours(9,0,0,0);state.tables.tasks.push(touch({id:newId(),title:step.title,contact_id:contact.id,due_at:due.toISOString().slice(0,16),priority:'Medium',status:'open',notes:'',action_plan_id:plan.id,reminder_minutes:60,created_at:now(),completed_at:null}));if(/send|email|text|message/i.test(step.title)){const message=suggestedMessage(contact,step.title);state.tables.communication_drafts.push(touch({id:newId(),contact_id:contact.id,...message,status:'draft',source:`${plan.name}: ${step.title}`,due_at:due.toISOString().slice(0,16),created_at:now(),updated_at:now()}))}}return plan.steps.length}
function ensureTransaction(state,tx){const fields=[['Earnest money due',tx.contract_date],['Inspection',tx.inspection_date],['Appraisal',tx.appraisal_date],['Financing approval',tx.financing_deadline],['Final Walk Through',tx.final_walkthrough_date],['Closing',tx.closing_date]];for(const [title,due] of fields)if(!state.tables.transaction_checklist.some(x=>x.transaction_id===tx.id&&x.title===title))state.tables.transaction_checklist.push(touch({id:newId(),transaction_id:tx.id,title,due_date:due||null,responsible_party:'',status:'open',notes:'',sort_order:99,completed_at:null,created_at:now()}))}
function search(state,q){const text=q.toLowerCase(),contains=x=>JSON.stringify(x).toLowerCase().includes(text);return {contacts:list(state,'contacts').filter(contains).slice(0,25),properties:[...state.tables.listings.filter(contains).map(x=>({kind:'Listing',id:x.id,label:x.address,status:x.status,detail:x.status})),...state.tables.transactions.filter(contains).map(x=>({kind:'Transaction',id:x.id,label:x.property,status:x.status,detail:x.status}))].slice(0,25),stages:list(state,'opportunities').filter(contains).slice(0,25)}}
function remove(state,table,id){const row=state.tables[table]?.find(x=>x.id===id);if(!row)return;state.tables[table]=state.tables[table].filter(x=>x.id!==id);state.deleted[table]??={};state.deleted[table][id]=now();if(table==='contacts'){for(const t of ['opportunities','activities'])for(const child of state.tables[t].filter(x=>x.contact_id===id))remove(state,t,child.id);for(const t of ['tasks','listings','transactions'])state.tables[t]=state.tables[t].map(x=>touch({...x,...(x.contact_id===id?{contact_id:null}:{}),...(x.seller_id===id?{seller_id:null}:{}),...(x.buyer_id===id?{buyer_id:null}:{})}))}if(table==='transactions')for(const t of ['transaction_checklist','transaction_documents'])for(const child of state.tables[t].filter(x=>x.transaction_id===id))remove(state,t,child.id)}
function mergeContact(state,primaryId,duplicateId){
 const primary=state.tables.contacts.find(x=>x.id===primaryId),duplicate=state.tables.contacts.find(x=>x.id===duplicateId);
 if(!primary||!duplicate||primaryId===duplicateId)throw Error('Both contact records are required');
 const later=(a,b)=>[a,b].filter(Boolean).sort().pop()||'',earlier=(a,b)=>[a,b].filter(Boolean).sort()[0]||'';
 const notes=[primary.notes,duplicate.notes].map(x=>String(x||'').trim()).filter(Boolean);
 const merged={...primary};
 for(const key of ['first_name','last_name','phone','email','partner','preferred_contact','source','budget','area','important_feature','pool'])if(!merged[key]&&duplicate[key])merged[key]=duplicate[key];
 for(const key of ['budget_min','budget_max','bedrooms','bathrooms'])merged[key]=Math.max(Number(primary[key]||0),Number(duplicate[key]||0));
 merged.roles=[...new Set([...(primary.roles||[]),...(duplicate.roles||[])])];
 merged.tags=[...new Set([...(primary.tags||[]),...(duplicate.tags||[])].map(x=>String(x).trim()).filter(Boolean))];
 merged.notes=[...new Set(notes)].join('\n\n');
 merged.last_contact=later(primary.last_contact,duplicate.last_contact);
 merged.next_follow_up=later(primary.next_follow_up,duplicate.next_follow_up);
 merged.created_at=earlier(primary.created_at,duplicate.created_at)||primary.created_at;
 Object.assign(primary,touch({...merged,updated_at:now()}));
 for(const table of ['opportunities','activities','tasks','communication_drafts','contact_documents','notifications'])for(const row of state.tables[table]||[])if(Number(row.contact_id)===duplicateId)Object.assign(row,touch({...row,contact_id:primaryId}));
 for(const row of state.tables.listings||[])if(Number(row.seller_id)===duplicateId)Object.assign(row,touch({...row,seller_id:primaryId}));
 for(const row of state.tables.transactions||[]){const update={};if(Number(row.buyer_id)===duplicateId)update.buyer_id=primaryId;if(Number(row.seller_id)===duplicateId)update.seller_id=primaryId;if(Object.keys(update).length)Object.assign(row,touch({...row,...update}))}
 const seen=new Map();
 for(const opportunity of [...state.tables.opportunities].filter(x=>Number(x.contact_id)===primaryId)){
  const key=[opportunity.type,opportunity.stage,opportunity.title,Number(opportunity.value||0),opportunity.status].join('|'),existing=seen.get(key);
  if(!existing)seen.set(key,opportunity);else{const keep=String(existing.updated_at||existing._modified_at||'')>=String(opportunity.updated_at||opportunity._modified_at||'')?existing:opportunity,drop=keep===existing?opportunity:existing;seen.set(key,keep);remove(state,'opportunities',drop.id)}
 }
 remove(state,'contacts',duplicateId);
 return copy(primary)
}

async function localApi(path,opts={}){const state=await read(),method=opts.method||'GET',parts=path.split('?')[0].split('/').filter(Boolean),input=body(opts);
 if(path.startsWith('/dashboard'))return dashboard(state);if(path.startsWith('/search'))return search(state,new URLSearchParams(path.split('?')[1]).get('q')||'');if(path==='/export')return copy(state);
 if(parts[0]==='contacts'&&parts[2]==='apply-plan'&&method==='POST'){const contact=state.tables.contacts.find(x=>x.id===Number(parts[1])),created=contact?applyPlan(state,contact):0;await write(state);return {created}}
 if(parts[0]==='contacts'&&parts[2]==='merge'&&method==='POST'){const merged=mergeContact(state,Number(parts[1]),Number(input.duplicate_id));await write(state);return merged}
 if(parts[0]==='contacts'&&parts[2]==='documents'){const contactId=Number(parts[1]);if(method==='GET')return copy(state.tables.contact_documents.filter(x=>x.contact_id===contactId).map(({data,...x})=>x));if(method==='POST'){const row=touch({id:newId(),contact_id:contactId,filename:input.filename,mime_type:input.mime_type||'application/octet-stream',size_bytes:Math.round((input.data?.length||0)*.75),data:input.data,created_at:now()});state.tables.contact_documents.push(row);await write(state);const {data,...meta}=row;return meta}}
 if(parts[0]==='transactions'&&parts[2]==='documents'){const transactionId=Number(parts[1]);if(method==='GET')return copy(state.tables.transaction_documents.filter(x=>x.transaction_id===transactionId).map(({data,...x})=>x));if(method==='POST'){const row=touch({id:newId(),transaction_id:transactionId,filename:input.filename,mime_type:input.mime_type||'application/octet-stream',size_bytes:Math.round((input.data?.length||0)*.75),data:input.data,created_at:now()});state.tables.transaction_documents.push(row);await write(state);const {data,...meta}=row;return meta}}
 if(parts[0]==='transactions'&&parts[2]==='checklist'){const transactionId=Number(parts[1]),tx=state.tables.transactions.find(x=>x.id===transactionId);if(tx)ensureTransaction(state,tx);if(method==='GET'){await write(state);return copy(state.tables.transaction_checklist.filter(x=>x.transaction_id===transactionId))}if(method==='POST'){const row=touch({id:newId(),transaction_id:transactionId,title:input.title,due_date:input.due_date||null,responsible_party:input.responsible_party||'',status:'open',notes:input.notes||'',sort_order:Number(input.sort_order||99),completed_at:null,created_at:now()});state.tables.transaction_checklist.push(row);await write(state);return copy(row)}}
 const documentTable=parts[0]==='contact-documents'?'contact_documents':parts[0]==='transaction-documents'?'transaction_documents':null;if(documentTable&&method==='PUT'){const index=state.tables[documentTable].findIndex(x=>x.id===Number(parts[1]));if(index<0)throw Error('Document not found');state.tables[documentTable][index]=touch({...state.tables[documentTable][index],...input});await write(state);const {data,...meta}=state.tables[documentTable][index];return copy(meta)}if(documentTable&&method==='DELETE'){const deletedDocument=copy(state.tables[documentTable].find(x=>x.id===Number(parts[1])));remove(state,documentTable,Number(parts[1]));await write(state);if(deletedDocument)document.dispatchEvent(new CustomEvent('crm:document-delete',{detail:deletedDocument}));return {ok:true}}
 const table=parts[0],id=parts[1]?Number(parts[1]):null;if(!tableNames.includes(table))throw Error('Offline feature not found');if(method==='GET')return id?copy(state.tables[table].find(x=>x.id===id)):list(state,table);
 if(method==='POST'){const defaults=table==='tasks'?{status:'open',priority:'Medium',reminder_minutes:0,completed_at:null,reminder_sent_at:null}:table==='communication_drafts'?{status:'draft',channel:'Email',subject:'',body:'',source:'Manual'}:{};const row=touch({id:newId(),...defaults,...input,created_at:input.created_at||now(),updated_at:now()});if(table==='contacts'){row.tags??=[];row.roles??=[]}state.tables[table].push(row);if(table==='contacts'){for(const role of row.roles||[]){const type=String(role).toLowerCase();if(['buyer','seller'].includes(type))state.tables.opportunities.push(touch({id:newId(),contact_id:row.id,type,stage:'New Lead',title:`${role} opportunity`,value:0,details:{},status:'active',created_at:now(),updated_at:now()}))}if(input.apply_plan)applyPlan(state,row)}if(table==='activities'&&row.contact_id){const contact=state.tables.contacts.find(x=>x.id===Number(row.contact_id));if(contact)Object.assign(contact,touch({...contact,last_contact:row.occurred_at||now(),updated_at:now()}))}if(table==='transactions')ensureTransaction(state,row);await write(state);return copy(row)}
 if(method==='PUT'){const index=state.tables[table].findIndex(x=>x.id===id);if(index<0)throw Error('Record not found');state.tables[table][index]=touch({...state.tables[table][index],...input,updated_at:now()});await write(state);return copy(state.tables[table][index])}if(method==='DELETE'){remove(state,table,id);await write(state);return {ok:true}}throw Error('Offline operation not supported')}

async function keyFrom(passphrase,salt,usage){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,usage)}
const b64=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes))),unb64=text=>Uint8Array.from(atob(text),x=>x.charCodeAt(0));
function downloadBackupFile(file){const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
function offerBackupFile(file){
 const shade=document.createElement('div');shade.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(10,35,35,.55);display:grid;place-items:center;padding:20px';shade.innerHTML='<div style="width:min(460px,100%);background:#fff;border-radius:18px;padding:24px;color:#173737;box-shadow:0 20px 60px rgba(0,0,0,.25)"><h2 style="margin:0 0 10px">Backup ready</h2><p style="margin:0 0 18px;line-height:1.45">Save the file, or copy the encrypted backup and paste it into an Apple Note for transfer to your Mac.</p><div style="display:grid;gap:10px"><button id="copyBackupText" class="primary">Copy encrypted backup</button><button id="saveBackupFile" class="secondary">Save encrypted backup to Files</button><button id="cancelBackupFile" class="secondary">Cancel</button></div></div>';
 document.body.appendChild(shade);shade.querySelector('#cancelBackupFile').onclick=()=>shade.remove();shade.querySelector('#copyBackupText').onclick=async()=>{const text=await file.text();try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;area.style.cssText='position:fixed;opacity:0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}alert('Encrypted backup copied. Paste it into an Apple Note, then open that note on your Mac.');shade.remove()};shade.querySelector('#saveBackupFile').onclick=async()=>{if(!(navigator.share&&navigator.canShare?.({files:[file]}))){downloadBackupFile(file);alert(`Encrypted backup created: ${file.name}`);return}try{await navigator.share({files:[file],title:'Hearthstone CRM encrypted backup'});shade.remove()}catch(error){if(error.name!=='AbortError'){downloadBackupFile(file);alert('The share menu could not open, so the CRM used a standard download instead.')}}};
}
async function exportOfflineBackup(){const passphrase=prompt('Create a password for this encrypted CRM backup:');if(!passphrase)return;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFrom(passphrase,salt,['encrypt']),plain=new TextEncoder().encode(JSON.stringify(await read())),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain),payload={format:'hearthstone-encrypted-backup',version:1,salt:b64(salt),iv:b64(iv),data:b64(cipher)},filename=`hearthstone-crm-${new Date().toISOString().slice(0,10)}-encrypted.txt`,file=new File([JSON.stringify(payload)],filename,{type:'text/plain'});offerBackupFile(file)}
function merge(current,incoming){incoming.tables??={};for(const table of tableNames){current.tables[table]??=[];incoming.tables[table]??=[];const map=new Map(current.tables[table].map(x=>[String(x.id),x]));for(const row of incoming.tables[table]){const old=map.get(String(row.id)),a=old?Date.parse(old._modified_at||old.updated_at||old.created_at||0):0,b=Date.parse(row._modified_at||row.updated_at||row.created_at||0);if(!old||b>=a)map.set(String(row.id),old?.data&&!row.data?{...row,data:old.data}:row)}const deleted={...(current.deleted[table]||{}),...(incoming.deleted?.[table]||{})};current.deleted[table]=deleted;current.tables[table]=[...map.values()].filter(row=>!deleted[row.id]||Date.parse(row._modified_at||0)>Date.parse(deleted[row.id]))}return current}
async function importBackupText(text){const parsed=JSON.parse(text.trim());let incoming;if(parsed.format==='hearthstone-encrypted-backup'){const passphrase=prompt('Enter the backup password:');if(!passphrase)return false;const key=await keyFrom(passphrase,unb64(parsed.salt),['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(parsed.iv)},key,unb64(parsed.data));incoming=JSON.parse(new TextDecoder().decode(plain))}else if(parsed.tables)incoming=parsed;else{incoming=fresh();for(const table of tableNames)if(Array.isArray(parsed[table]))incoming.tables[table]=parsed[table].map(touch)}const before=(await read()).tables.contacts.length,merged=merge(await read(),incoming),after=merged.tables.contacts.length;await write(merged);alert(`CRM backup merged successfully. ${after-before} contact${after-before===1?'':'s'} added; ${after} total contacts on this device.`);location.reload();return true}
async function importOfflineBackup(){const input=document.createElement('input');input.type='file';input.accept='.hcrm,.json,.txt,application/json,text/plain';input.onchange=async()=>{try{await importBackupText(await input.files[0].text())}catch(error){alert('The backup could not be imported. Check the file and password.')}};input.click()}
function pasteOfflineBackup(){const shade=document.createElement('div');shade.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(10,35,35,.55);display:grid;place-items:center;padding:20px';shade.innerHTML='<div style="width:min(620px,100%);background:#fff;border-radius:18px;padding:24px;color:#173737;box-shadow:0 20px 60px rgba(0,0,0,.25)"><h2 style="margin:0 0 10px">Paste encrypted backup</h2><p style="margin:0 0 14px;line-height:1.45">Copy the entire encrypted backup from Apple Notes, paste it below, then merge it into this device.</p><textarea id="pastedBackupText" style="width:100%;min-height:180px;margin-bottom:12px" placeholder="Paste encrypted backup here"></textarea><div style="display:flex;gap:10px;flex-wrap:wrap"><button id="mergePastedBackup" class="primary" style="flex:1">Import and merge</button><button id="cancelPastedBackup" class="secondary">Cancel</button></div></div>';document.body.appendChild(shade);const area=shade.querySelector('#pastedBackupText');area.focus();shade.querySelector('#cancelPastedBackup').onclick=()=>shade.remove();shade.querySelector('#mergePastedBackup').onclick=async()=>{if(!area.value.trim())return alert('Paste the encrypted backup first.');try{await importBackupText(area.value);shade.remove()}catch{alert('The pasted backup could not be imported. Make sure you copied all of it and entered the correct password.')}}}
async function offlineDocumentUrl(url){const match=url.match(/\/(contact|transaction)-documents\/(\d+)/);if(!match)return url;const state=await read(),table=`${match[1]}_documents`,doc=state.tables[table].find(x=>x.id===Number(match[2]));if(!doc)return '';return doc.data||await window.crmCloudFiles?.fetchDocument(doc)||''}
async function downloadOfflineDocument(url){const match=url.match(/\/(contact|transaction)-documents\/(\d+)/);if(!match)return;const state=await read(),doc=state.tables[`${match[1]}_documents`].find(x=>x.id===Number(match[2]));if(!doc)return;try{const a=document.createElement('a');a.href=doc.data||await window.crmCloudFiles?.fetchDocument(doc);a.download=doc.filename;a.click()}catch(error){alert(error.message)}}
