const config={apiKey:'AIzaSyDJja4KxdCJ-GZ7lE_krRMoX7dF5RGtSKw',authDomain:'hearthstone-real-estate-crm.firebaseapp.com',projectId:'hearthstone-real-estate-crm',storageBucket:'hearthstone-real-estate-crm.firebasestorage.app',messagingSenderId:'694415647324',appId:'1:694415647324:web:f8bf3a1e9b529b0f1c3c99'};
firebase.initializeApp(config);
const params=new URLSearchParams(location.search),address=(params.get('address')||'Property Sign-In').slice(0,180),listingId=(params.get('listing')||'').slice(0,40);
document.querySelector('#propertyAddress').textContent=address;
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function safeUrl(value){if(!String(value||'').trim())return '';try{const url=new URL(value,location.href);return ['https:','http:'].includes(url.protocol)?url.href:''}catch{return ''}}
async function showMarketing(){if(!listingId)return;try{const snapshot=await firebase.firestore().collection('public_listings').doc(listingId).get();if(!snapshot.exists)return;const p=snapshot.data(),hero=safeUrl(p.hero_image_url),gallery=(p.gallery_urls||[]).map(safeUrl).filter(Boolean),links=[['View full listing',p.public_listing_url],['Virtual tour',p.virtual_tour_url],['Download property flyer',p.flyer_url],...(p.public_documents||[]).map((url,index)=>[`Public document ${index+1}`,url])].map(([label,url])=>[label,safeUrl(url)]).filter(x=>x[1]);const section=document.querySelector('#propertyMarketing');section.innerHTML=`${params.get('preview')==='1'?'<div class="preview-note">Visitor-page preview</div>':''}${hero?`<img class="property-hero" src="${escapeHtml(hero)}" alt="${escapeHtml(p.address)}">`:''}<div class="property-copy"><div class="eyebrow">PROPERTY DETAILS</div><h2>${escapeHtml(p.address||address)}</h2><div class="property-price">${money(p.current_price)}</div><div class="property-facts">${p.bedrooms?`<span>${escapeHtml(p.bedrooms)} bedrooms</span>`:''}${p.bathrooms?`<span>${escapeHtml(p.bathrooms)} bathrooms</span>`:''}${p.square_feet?`<span>${Number(p.square_feet).toLocaleString()} sq ft</span>`:''}${p.pool?`<span>Pool: ${escapeHtml(p.pool)}</span>`:''}${p.mls?`<span>MLS ${escapeHtml(p.mls)}</span>`:''}</div>${p.public_description?`<p class="property-description">${escapeHtml(p.public_description)}</p>`:''}${p.feature_highlights?.length?`<h3>Property highlights</h3><ul class="feature-list">${p.feature_highlights.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:''}</div>${gallery.length?`<div class="property-gallery">${gallery.map((url,index)=>`<img src="${escapeHtml(url)}" alt="Property photo ${index+1}" loading="lazy">`).join('')}</div>`:''}${links.length?`<div class="property-links">${links.map(([label,url])=>`<a class="btn" href="${escapeHtml(url)}" target="_blank" rel="noopener">${escapeHtml(label)}</a>`).join('')}</div>`:''}`;section.hidden=false;section.scrollIntoView({behavior:'smooth',block:'start'})}catch(error){console.error('Marketing page:',error)}}
if(params.get('preview')==='1'){document.querySelector('#signCard').hidden=true;showMarketing()}
document.querySelector('#signInForm').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;button.textContent='Submitting…';const data=Object.fromEntries(new FormData(form));try{await firebase.firestore().collection('open_house_submissions').add({first_name:String(data.first_name||'').slice(0,80),last_name:String(data.last_name||'').slice(0,80),phone:String(data.phone||'').slice(0,40),email:String(data.email||'').slice(0,160),role:String(data.role||'Buyer').slice(0,30),timeframe:String(data.timeframe||'').slice(0,40),budget_min:Number(data.budget_min||0),budget_max:Number(data.budget_max||0),bedrooms:Number(data.bedrooms||0),pool:String(data.pool||'').slice(0,10),area:String(data.area||'').slice(0,120),important_feature:String(data.important_feature||'').slice(0,180),agent_status:String(data.agent_status||'').slice(0,20),preapproved:String(data.preapproved||'').slice(0,20),consent:data.consent==='on',listing_id:listingId,listing_address:address,source:'Open House',imported:false,created_at:firebase.firestore.FieldValue.serverTimestamp()});form.hidden=true;document.querySelector('#signSuccess').hidden=false;await showMarketing()}catch(error){console.error(error);alert('The sign-in could not be submitted. Please check your internet connection and try again.');button.disabled=false;button.textContent='Complete sign-in'}};
