const firebaseConfig={apiKey:'AIzaSyDJja4KxdCJ-GZ7lE_krRMoX7dF5RGtSKw',authDomain:'hearthstone-real-estate-crm.firebaseapp.com',projectId:'hearthstone-real-estate-crm',storageBucket:'hearthstone-real-estate-crm.firebasestorage.app',messagingSenderId:'694415647324',appId:'1:694415647324:web:f8bf3a1e9b529b0f1c3c99'};
firebase.initializeApp(firebaseConfig);
const params=new URLSearchParams(location.search),listingId=params.get('listing')||'',fallbackAddress=params.get('address')||'Listing',slides=document.querySelector('#slides');let photos=[],index=0,timer,playing=true;
const money=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function draw(){document.querySelectorAll('.slide').forEach((slide,i)=>slide.classList.toggle('active',i===index));document.querySelector('#counter').textContent=`${photos.length?index+1:0} / ${photos.length}`}
function advance(step=1){if(!photos.length)return;index=(index+step+photos.length)%photos.length;draw();restart()}
function restart(){clearInterval(timer);if(playing&&photos.length>1)timer=setInterval(()=>{index=(index+1)%photos.length;draw()},7000)}
async function load(){try{const snap=await firebase.firestore().collection('public_listings').doc(listingId).get(),p=snap.exists?snap.data():{};photos=[p.hero_image_url,...(p.gallery_urls||[])].filter(Boolean);document.querySelector('#address').textContent=p.address||fallbackAddress;document.title=`${p.address||fallbackAddress} | Slideshow`;document.querySelector('#facts').innerHTML=[p.current_price?money(p.current_price):'',p.bedrooms?`${p.bedrooms} bedrooms`:'',p.bathrooms?`${p.bathrooms} bathrooms`:'',p.square_feet?`${Number(p.square_feet).toLocaleString()} sq ft`:'',p.mls?`MLS ${p.mls}`:''].filter(Boolean).map(x=>`<span>${x}</span>`).join('');slides.innerHTML=photos.map((url,i)=>`<div class="slide ${i===0?'active':''}" style="background-image:url('${String(url).replace(/'/g,'%27')}')"></div>`).join('');document.querySelector('#empty').hidden=!!photos.length;const signUrl=new URL('./open-house.html',location.href);signUrl.searchParams.set('listing',listingId);signUrl.searchParams.set('address',p.address||fallbackAddress);document.querySelector('#qr').src=`https://quickchart.io/qr?size=300&margin=1&text=${encodeURIComponent(signUrl.href)}`;draw();restart()}catch(error){console.error(error);document.querySelector('#empty').hidden=false}}
document.querySelector('#previous').onclick=()=>advance(-1);document.querySelector('#next').onclick=()=>advance(1);document.querySelector('#pause').onclick=()=>{playing=!playing;document.querySelector('#pause').textContent=playing?'Ⅱ':'▶';restart()};document.querySelector('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')advance(-1);if(event.key==='ArrowRight')advance(1);if(event.key===' '){event.preventDefault();document.querySelector('#pause').click()}});load();
