const firebaseConfig={apiKey:'AIzaSyDJja4KxdCJ-GZ7lE_krRMoX7dF5RGtSKw',authDomain:'hearthstone-real-estate-crm.firebaseapp.com',projectId:'hearthstone-real-estate-crm',storageBucket:'hearthstone-real-estate-crm.firebasestorage.app',messagingSenderId:'694415647324',appId:'1:694415647324:web:f8bf3a1e9b529b0f1c3c99'};
firebase.initializeApp(firebaseConfig);
document.querySelector('header .brand').textContent='ERIC HEPPLE · PARADISE PROPERTY BROKERS INC';
const params=new URLSearchParams(location.search),listingId=params.get('listing')||'',fallbackAddress=params.get('address')||'Listing',slides=document.querySelector('#slides');let photos=[],index=0,timer,playing=true;
const money=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function draw(){document.querySelectorAll('.slide').forEach((slide,i)=>slide.classList.toggle('active',i===index));document.querySelector('#counter').textContent=`${photos.length?index+1:0} / ${photos.length}`}
function advance(step=1){if(!photos.length)return;index=(index+step+photos.length)%photos.length;draw();restart()}
function restart(){clearInterval(timer);if(playing&&photos.length>1)timer=setInterval(()=>{index=(index+1)%photos.length;draw()},7000)}
async function load(){try{const snap=await firebase.firestore().collection('public_listings').doc(listingId).get(),p=snap.exists?snap.data():{};photos=[p.hero_image_url,...(p.gallery_urls||[])].filter(Boolean);document.querySelector('#address').textContent=p.address||fallbackAddress;document.title=`${p.address||fallbackAddress} | Slideshow`;document.querySelector('#facts').innerHTML=[p.current_price?money(p.current_price):'',p.bedrooms?`${p.bedrooms} bedrooms`:'',p.bathrooms?`${p.bathrooms} bathrooms`:'',p.square_feet?`${Number(p.square_feet).toLocaleString()} sq ft`:'',p.mls?`MLS ${p.mls}`:''].filter(Boolean).map(x=>`<span>${x}</span>`).join('');slides.innerHTML=photos.map((url,i)=>`<div class="slide ${i===0?'active':''}" style="background-image:url('${String(url).replace(/'/g,'%27')}')"></div>`).join('');
const empty=document.querySelector('#empty');empty.hidden=!!photos.length;empty.style.display=photos.length?'none':'grid';const signUrl=new URL('./open-house.html',location.href);signUrl.searchParams.set('listing',listingId);signUrl.searchParams.set('address',p.address||fallbackAddress);document.querySelector('#qr').src=`https://quickchart.io/qr?size=300&margin=1&text=${encodeURIComponent(signUrl.href)}`;draw();restart()}catch(error){console.error(error);const empty=document.querySelector('#empty');empty.hidden=false;empty.style.display='grid'}}
document.querySelector('#previous').onclick=()=>advance(-1);document.querySelector('#next').onclick=()=>advance(1);document.querySelector('#pause').onclick=()=>{playing=!playing;document.querySelector('#pause').textContent=playing?'Ⅱ':'▶';restart()};document.querySelector('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();document.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')advance(-1);if(event.key==='ArrowRight')advance(1);if(event.key===' '){event.preventDefault();document.querySelector('#pause').click()}});load();
const overlay=document.querySelector('#signInOverlay'),slideForm=document.querySelector('#slideSignInForm'),slideSuccess=document.querySelector('#slideSignSuccess');
function currentAddress(){return document.querySelector('#address').textContent||fallbackAddress}
function openTouchSignIn(){clearInterval(timer);document.querySelector('#signInProperty').textContent=currentAddress();slideForm.hidden=false;slideSuccess.hidden=true;overlay.hidden=false;setTimeout(()=>slideForm.querySelector('input')?.focus(),50)}
function closeTouchSignIn(){overlay.hidden=true;restart()}
document.querySelector('#touchSignIn').onclick=openTouchSignIn;
document.querySelector('#closeSignIn').onclick=closeTouchSignIn;
document.querySelector('#returnToSlides').onclick=closeTouchSignIn;
overlay.onclick=event=>{if(event.target===overlay)closeTouchSignIn()};
slideForm.onsubmit=async event=>{event.preventDefault();const button=slideForm.querySelector('.submit-signin'),data=Object.fromEntries(new FormData(slideForm));button.disabled=true;button.textContent='Submitting…';try{await firebase.firestore().collection('open_house_submissions').add({first_name:String(data.first_name||'').slice(0,80),last_name:String(data.last_name||'').slice(0,80),phone:String(data.phone||'').slice(0,40),email:String(data.email||'').slice(0,160),role:'Buyer',timeframe:String(data.timeframe||'').slice(0,40),budget_min:0,budget_max:0,bedrooms:0,pool:'',area:'',important_feature:'',agent_status:String(data.agent_status||'').slice(0,20),preapproved:String(data.preapproved||'').slice(0,20),consent:true,listing_id:String(listingId).slice(0,40),listing_address:String(currentAddress()).slice(0,180),source:'Open House',imported:false,created_at:firebase.firestore.FieldValue.serverTimestamp()});slideForm.hidden=true;slideSuccess.hidden=false;slideForm.reset();button.disabled=false;button.textContent='Complete Sign-In'}catch(error){console.error(error);alert('The sign-in could not be submitted. Please check the internet connection and try again.');button.disabled=false;button.textContent='Complete Sign-In'}};
